#spring.datasource.url=jdbc:postgresql://ec2-54-173-77-184.compute-1.amazonaws.com:5432/dfg3g04640bb4u
#spring.datasource.username= vmtzyfjqbeztqg
#spring.datasource.password=48030fcb489d4e2cea66339a71cc7712b329de084692079de5dfb1fb83f094b6
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
#spring.thymeleaf.cache=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
#server.error.include-stacktrace=always

spring:
  datasource:
    url: 'jdbc:postgresql://ec2-54-173-77-184.compute-1.amazonaws.com:5432/dfg3g04640bb4u'
    username: vmtzyfjqbeztqg
    password: 48030fcb489d4e2cea66339a71cc7712b329de084692079de5dfb1fb83f094b6
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  error:
    include-stacktrace: always
springdoc:
  packagesToScan: com.example
  pathsToMatch: /**

